seed: 123
env_id: assembly-v2
env_name: metaworld

exp_name: ${algo_name}_e-${env_id}_t-${total_timesteps}_s-${seed}

exp_dir: null
results_dir: results
video_dir: videos
log_dir: logs
ckpt_dir: ckpts
eval_dir: evals
ckpt_prefix: "ckpt"

wandb:
  project: sb3_mw
  entity: aliangdw
  tags: 
    - mw
    - ${env_id}
    - ${algo_name}]
  notes: "mw policy"
  sync_tensorboard: True
  monitor_gym: True
  save_code: True

mode: train
n_train_envs: 20
n_eval_envs: 20
n_eval_episodes: 20
n_eval_videos_render: 9

progress_bar: False
total_timesteps: 10_000_000

num_evals: 30
eval_freq: -1
num_save_ckpts: 10
save_ckpt_freq: -1
save_replay_buffer: True
gradient_save_freq: 10_000

use_wandb: False

algo_name: sac

debug: False

env_kwargs:
  n_frame_stack: 4
  max_episode_steps: 200

# for replaying from ckpt
ckpt_file_name: null
ckpt_step: null
num_episodes_replay: 1
fps: 10

# for offline dataset saving
data_dir: /scr/shared/clam

# for data collection
save_imgs: False


defaults:
  - _self_
  - algo: sac
  - override hydra/job_logging: disabled
  - override hydra/launcher: local

# set the directory where the output files get saved
hydra:
  job:
    name: ${exp_name}

  output_subdir: null
  run:
    dir: results/${exp_name}/${now:%Y-%m-%d}-${now:%H-%M-%S}
  
  sweep:
    dir: results/${now:%Y-%m-%d}-${now:%H-%M-%S}
    subdir: ${exp_name}
